version: 2.1
orbs:
  macos: circleci/macos@2.0
workflows:
  version: 2
  appstore-submit:
    jobs:
      - appstore_submit:
          filters:
            branches:
              only: main
jobs:
  appstore_submit:
    macos:
      xcode: "14.2.0"
    
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: appstore_submit
      
    steps:
      - checkout
      
      - run:
          name: Install Dependencies
          command: |
            gem install bundler
            bundle install
      
      - run:
          name: Run Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      
      - store_artifacts:
          path: output
          destination: output-artifacts
